// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-realworld/app/article/internal/biz"
	"kratos-realworld/app/article/internal/conf"
	"kratos-realworld/app/article/internal/data"
	"kratos-realworld/app/article/internal/server"
	"kratos-realworld/app/article/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, jwt *conf.Jwt, register *conf.Register, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	articleRepo := data.NewArticleRepo(dataData, logger)
	commentRepo := data.NewCommentRepo(dataData, logger)
	tagRepo := data.NewTagRepo(dataData, logger)
	discovery := server.NewDiscovery(register)
	userClient := biz.NewUserClient(discovery)
	articleUseCase := biz.NewArticleUseCase(articleRepo, commentRepo, tagRepo, userClient, logger)
	articleService := service.NewArticleService(articleUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, articleService, logger)
	httpServer := server.NewHTTPServer(confServer, jwt, articleService, logger)
	registrar := server.NewRegistrar(register)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
